language: python
cache: pip
sudo: false
python:
- '3.6'
- '3.5'
- '2.7'
addons:
  postgresql: "9.4"
env:
- REQ="Django>=1.9,<1.10 django-cte-forest<0.2"
- REQ="Django>=1.10,<1.11 django-cte-forest"
- REQ="Django>=1.11,<2.0 django-cte-forest"
- REQ="Django>=2.0,<2.1 django-cte-forest"
- REQ="https://github.com/django/django/archive/master.zip#egg=Django django-cte-forest"
matrix:
  allow_failures:
    - env: REQ="https://github.com/django/django/archive/master.zip#egg=Django django-cte-forest"
  exclude:
    - python: '2.7'
      env: REQ="Django>=2.0,<2.1 django-cte-forest"
    - python: '2.7'
      env: REQ="https://github.com/django/django/archive/master.zip#egg=Django django-cte-forest"
install:
- pip install -U pip wheel
- pip install $REQ django-ckeditor django-content-editor
  django-versatileimagefield html-sanitizer pytz requests psycopg2
- python setup.py install
script: cd tests && ./manage.py test testapp && cd ..
